name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main           # Despliega a producción cuando haya un push a main
      - development    # Despliega a desarrollo cuando haya un push a development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3  
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: |
          CI=false npm run build

      - name: Set up Firebase CLI and authenticate
        run: |
          npm install -g firebase-tools
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > $GOOGLE_APPLICATION_CREDENTIALS
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Deploy to Firebase Hosting (Production)
        if: github.ref == 'refs/heads/main'   # Despliega a producción solo si el push es a main
        run: |
          firebase use --project ${{ secrets.FIREBASE_PROJECT_ID }}
          firebase deploy --only hosting:prod-book-social

      - name: Deploy to Firebase Hosting (Development)
        if: github.ref == 'refs/heads/development'   # Despliega a desarrollo solo si el push es a development
        run: |
          firebase use --project ${{ secrets.FIREBASE_PROJECT_ID }}
          firebase deploy --only hosting:dev-book-social
